local math=setmetatable({random=function(Arg1,Arg2,DIV) DIV=DIV or 1 return math.random(Arg1*DIV,Arg2*DIV)/DIV end,CosSin=function(Arg) return (math.sin(Arg/2)*math.cos(Arg/2)) end,},{__index=math,})
local CFrame=setmetatable({Angles=function(Arg1,Arg2,Arg3,Angles) if not Angles then return CFrame.Angles(Arg1,Arg2,Arg3) else return CFrame.Angles(math.rad(Arg1),math.rad(Arg2),math.rad(Arg3)) end end,},{__index=CFrame,})
local Instance=setmetatable({new=function(type,args) local instance=Instance.new(type) if args then if string.lower(typeof(args)) == "instance" then instance.Parent=args elseif string.lower(typeof(args))=="table" then for i,v in pairs(args) do pcall(function() instance[i]=v end) end end end return instance end,Remove=function(Instance_,Time) if string.lower(typeof(Instance_))=="instance" then game:GetService("Debris"):AddItem(Instance_,Time or 0) elseif string.lower(typeof(Instance_))=="table" then table.foreach(Instance_,function(_,v) game:GetService("Debris"):AddItem(v,Time or 0) end) end end},{__index=Instance,})
local ins=Instance.new
local v3=Vector3.new
local v2=Vector2.new
local cf=CFrame.new
local angles=CFrame.Angles
local ud=UDim.new
local ud2=UDim2.new
local c3=Color3.new
local rgb=Color3.fromRGB
local hsv=Color3.fromHSV
local bc=BrickColor.new
local bcRandom=BrickColor.Random
local palette=BrickColor.palette
local cs=ColorSequence.new
local ns=NumberSequence.new
local nsk=NumberSequenceKeypoint.new
local nr=NumberRange.new
local random=math.random
local rad=math.rad
local sin=math.sin
local cos=math.cos
local tan=math.tan
local CosSin=math.CosSin
local floor=math.floor
local pi=math.floor
local abs=math.abs
local sqrt=math.sqrt
local clamp=math.clamp
local ray=Ray.new
local huge=math.huge
return {
	Equip={
		Waits={
			[1]=.15,
		},
		[1]={
			{"nec",{C1=CFrame.Angles(math.rad(-7.5),math.rad(10),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C1=CFrame.new(0,0,0.1)*CFrame.Angles(math.rad(5),math.rad(-10),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(0,0.2,0.75)*CFrame.Angles(math.rad(-45),math.rad(0),math.rad(-20))*CFrame.Angles(math.rad(0),math.rad(70),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C1=CFrame.new(0.1,-0.1,0)*CFrame.Angles(math.rad(-5),math.rad(5),math.rad(-5))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C1=CFrame.new(0,0,-0.1)*CFrame.Angles(math.rad(-5),math.rad(10),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(-7),math.rad(10),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
		}
	},
	Swing1={
		Waits={
			[1]=.15,
			[2]=.05,
			[3]=.05,
			[4]=.15
		},
		[1]={
			{"nec",{C1=CFrame.Angles(math.rad(0),math.rad(20),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(0.25,-0.35,0.1)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(90))*CFrame.Angles(math.rad(-10),math.rad(-0),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,0)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(-5))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(5),math.rad(5),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,-0.15)*CFrame.Angles(math.rad(-10),math.rad(7.5),math.rad(-2.5))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
		},
		[2]={
			{"nec",{C1=CFrame.Angles(math.rad(0),math.rad(10),math.rad(0))},{.05,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"rutj",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(-10),math.rad(0))},{.05,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"rs",{C0=CFrame.new(0.25,-0.35,-0.1)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(90))*CFrame.Angles(math.rad(10),math.rad(-0),math.rad(0))},{.05,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,0)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(-7.5))},{.05,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.125,-0.1)*CFrame.Angles(math.rad(-5),math.rad(-2.5),math.rad(0))},{.05,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,-0.15)*CFrame.Angles(math.rad(-5),math.rad(7.5),math.rad(-2.5))},{.05,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
		},
		[3]={
			{"nec",{C1=CFrame.Angles(math.rad(-5),math.rad(-15),math.rad(0))},{.05,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0,0,-0.3)*CFrame.Angles(math.rad(-5),math.rad(15),math.rad(0))},{.05,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.25,-0.35,-0.3)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(90))*CFrame.Angles(math.rad(45),math.rad(-5),math.rad(0))},{.05,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,0.1)*CFrame.Angles(math.rad(-10),math.rad(0),math.rad(-7.5))},{.05,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.35,-0.25)*CFrame.Angles(math.rad(-15),math.rad(-7.5),math.rad(0))},{.05,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,-0.15)*CFrame.Angles(math.rad(-5),math.rad(-5),math.rad(-2.5))},{.05,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[4]={
			{"nec",{C1=CFrame.Angles(math.rad(-5),math.rad(-55),math.rad(0))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0,-0.1,-0.8)*CFrame.Angles(math.rad(-7.5),math.rad(55),math.rad(0))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(-.2,-0.35,-0.65)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(90))*CFrame.Angles(math.rad(165),math.rad(-5),math.rad(0))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,0.1)*CFrame.Angles(math.rad(-20),math.rad(0),math.rad(-15))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.Angles(math.rad(2.5),math.rad(-35),math.rad(5))*CFrame.new(0,0.1,-0.25)},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,-0.15)*CFrame.Angles(math.rad(-2.5),math.rad(-25),math.rad(-2.5))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
		}
	},
	Swing2={
		Waits={
			[1]=.15,
			[2]=.1,
			[3]=.075,
			[4]=.1,
			[5]=.075,
			[6]=.125
		},
		[1]={
			{"nec",{C1=CFrame.Angles(math.rad(-10),math.rad(10),math.rad(5))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C1=CFrame.new(-0.35,-0.15,-0.1)*CFrame.Angles(math.rad(-5),math.rad(15),math.rad(10))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(-0.5,-0.35,-0.75)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(-80))*CFrame.Angles(math.rad(0),math.rad(90),math.rad(10))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,-0.05)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(-10))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C1=CFrame.new(0,0,-0.1)*CFrame.Angles(math.rad(-5),math.rad(-10),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.25,-0.5)*CFrame.Angles(math.rad(-10),math.rad(10),math.rad(-5))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
		},
		[2]={
			{"nec",{C1=CFrame.Angles(math.rad(-10),math.rad(-10),math.rad(-5))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"rutj",{C1=CFrame.new(0.35,-0.05,0.05)*CFrame.Angles(math.rad(2.5),math.rad(-25),math.rad(-10))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"rs",{C0=CFrame.new(0.4,-0.35,-0.5)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(50))*CFrame.Angles(math.rad(0),math.rad(90),math.rad(10))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,-0.05)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(-10))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.1,-0.1)*CFrame.Angles(math.rad(-2.5),math.rad(-20),math.rad(0))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.5,-0.5)*CFrame.Angles(math.rad(-20),math.rad(15),math.rad(-7.5))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
		},
		[3]={
			{"nec",{C1=CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-7.5))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0.35,-0.05,0.05)*CFrame.Angles(math.rad(2.5),math.rad(-115),math.rad(-10))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.4,-0.35,-0.15)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(80))*CFrame.Angles(math.rad(0),math.rad(90),math.rad(10))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.2,-0.15,-0.15)*CFrame.Angles(math.rad(35),math.rad(-3),math.rad(-20))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.1,-0.1)*CFrame.Angles(math.rad(2.5),math.rad(-20),math.rad(0))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.5,-0.5)*CFrame.Angles(math.rad(-20),math.rad(15),math.rad(-7.5))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[4]={
			{"nec",{C1=CFrame.Angles(math.rad(5),math.rad(-30),math.rad(-7.5))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0.5,-0.05,-0.15)*CFrame.Angles(math.rad(2.5),math.rad(-225),math.rad(-15))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.4,-0.35,-0.15)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(80))*CFrame.Angles(math.rad(0),math.rad(90),math.rad(10))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.2,-0.15,-0.15)*CFrame.Angles(math.rad(35),math.rad(-3),math.rad(-30))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.1,-0.1)*CFrame.Angles(math.rad(2.5),math.rad(-20),math.rad(0))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.4,-0.5)*CFrame.Angles(math.rad(5),math.rad(5),math.rad(-7.5))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[5]={
			{"nec",{C1=CFrame.Angles(math.rad(5),math.rad(-30),math.rad(-7.5))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0.75,-0.05,-0)*CFrame.Angles(math.rad(2.5),math.rad(-295),math.rad(-15))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.4,-0.35,-0.15)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(80))*CFrame.Angles(math.rad(0),math.rad(90),math.rad(10))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.2,-0.15,-0.15)*CFrame.Angles(math.rad(35),math.rad(-3),math.rad(-30))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.1,-0.1)*CFrame.Angles(math.rad(2.5),math.rad(-30),math.rad(0))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.4,-0.5)*CFrame.Angles(math.rad(15),math.rad(-5),math.rad(7.5))},{.075,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[6]={
			{"nec",{C1=CFrame.Angles(math.rad(5),math.rad(-10),math.rad(0))},{.125,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0.5,-0.25,0.15)*CFrame.Angles(math.rad(-2.5),math.rad(-5),math.rad(-15))},{.125,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.4,-0.35,0.075)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(100))*CFrame.Angles(math.rad(0),math.rad(90),math.rad(10))},{.125,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.2,-0.15,-0.15)*CFrame.Angles(math.rad(15),math.rad(-10),math.rad(15))},{.125,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0.1,0.3,-0.35)*CFrame.Angles(math.rad(-5),math.rad(-30),math.rad(0))},{.125,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,-0.25)*CFrame.Angles(math.rad(15),math.rad(-15),math.rad(15))},{.125,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
		}
	},
	Grab={
		Waits={
			[1]=.1,
			[2]=.15
		},
		[1]={
			{"nec",{C1=CFrame.Angles(math.rad(0),math.rad(10),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(-10),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(-0.5,-0.5,0)*CFrame.Angles(math.rad(95),math.rad(20),math.rad(35))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0.25,-0.35,0.25)*CFrame.Angles(math.rad(45),math.rad(-30),math.rad(10))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(5),math.rad(5),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
		},
		[2]={
			{"nec",{C1=CFrame.Angles(math.rad(0),math.rad(-20),math.rad(0))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C1=CFrame.new(0,0,-0.5)*CFrame.Angles(math.rad(-5),math.rad(20),math.rad(0))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(-0.35,-0.1,-0.85)*CFrame.Angles(math.rad(100),math.rad(20),math.rad(-20))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0.25,-0.35,0.25)*CFrame.Angles(math.rad(45),math.rad(-30),math.rad(10))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C1=CFrame.Angles(math.rad(-15),math.rad(-35),math.rad(0))*CFrame.new(0,0.4,-0.25)},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,-0.1)*CFrame.Angles(math.rad(-7.5),math.rad(5),math.rad(0))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
		}
	},
	Grab_Throw={
		Waits={
			[1]=.15,
			[2]=.125,
			[3]=.5
		},
		[1]={
			{"nec",{C1=CFrame.Angles(math.rad(20),math.rad(-20),math.rad(10))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C1=CFrame.new(0,0,0.35)*CFrame.Angles(math.rad(10),math.rad(-20),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(0.25,0.35,-0.5)*CFrame.Angles(math.rad(170),math.rad(0),math.rad(0))*CFrame.Angles(math.rad(0),math.rad(90),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(-10),math.rad(15),math.rad(-5))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C1=CFrame.new(0,0,-0.35)*CFrame.Angles(math.rad(-10),math.rad(15),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(-10),math.rad(25),math.rad(2.5))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
		},
		[2]={
			{"nec",{C1=CFrame.Angles(math.rad(-20),math.rad(-20),math.rad(-5))},{.15,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0.25,-1.25,-0.2)*CFrame.Angles(math.rad(-40),math.rad(20),math.rad(0))},{.15,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.25,-0.45,-0.5)*CFrame.Angles(math.rad(70),math.rad(0),math.rad(20))*CFrame.Angles(math.rad(0),math.rad(90),math.rad(0))},{.15,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.15,-0.25,-0.2)*CFrame.Angles(math.rad(50),math.rad(-15),math.rad(-5))},{.15,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,1.4,-0.5)*CFrame.Angles(math.rad(10),math.rad(-15),math.rad(0))},{.15,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(-0.1,0.1,-1)*CFrame.Angles(math.rad(-40),math.rad(5),math.rad(2.5))},{.15,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
		},
		[3]={
			{"nec",{C1=CFrame.Angles(math.rad(-20),math.rad(-20),math.rad(-5))},{.5,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0.25,-1.25,-0.2)*CFrame.Angles(math.rad(-40),math.rad(20),math.rad(0))},{.5,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.25,-0.45,-0.5)*CFrame.Angles(math.rad(70),math.rad(0),math.rad(20))*CFrame.Angles(math.rad(0),math.rad(90),math.rad(0))},{.5,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.15,-0.25,-0.2)*CFrame.Angles(math.rad(50),math.rad(-15),math.rad(-5))},{.5,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,1.4,-0.5)*CFrame.Angles(math.rad(10),math.rad(-15),math.rad(0))},{.5,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(-0.1,0.1,-1)*CFrame.Angles(math.rad(-40),math.rad(5),math.rad(2.5))},{.5,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
		}
	},
	TBeam={
		Waits={
			[1]=.1,
			[2]=.15,
			[3]=.3
		},
		[1]={
			{"nec",{C1=CFrame.Angles(math.rad(0),math.rad(-10),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rutj",{C1=CFrame.new(-0.1,0,-0.35)*CFrame.Angles(math.rad(0),math.rad(45),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rs",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"ls",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.2,-0.25)*CFrame.Angles(math.rad(-10),math.rad(-10),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
		},
		[2]={
			{"nec",{C1=CFrame.Angles(math.rad(0),math.rad(-90),math.rad(0))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(-0.5,0,-0.75)*CFrame.Angles(math.rad(-5),math.rad(90),math.rad(0))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.5,-0.35,0)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(95))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,0)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(-5))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0,-0.05)*CFrame.Angles(math.rad(5),math.rad(-60),math.rad(10))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(5),math.rad(0))},{.15,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
		},
		[3]={
			{"nec",{C1=CFrame.Angles(math.rad(0),math.rad(-90),math.rad(0))},{.3,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(-0.5,0,-0.75)*CFrame.Angles(math.rad(-5),math.rad(90),math.rad(0))},{.3,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.5,-0.35,0)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(95))},{.3,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,0)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(-5))},{.3,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0,-0.05)*CFrame.Angles(math.rad(5),math.rad(-60),math.rad(10))},{.3,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(5),math.rad(0))},{.3,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		}
	},
	FBThrow={
		Waits={
			[1]=.1,
			[2]=.1,
			[3]=.1,
			[4]=.2,
			[5]=.2
		},
		[1]={
			{"nec",{C1=CFrame.Angles(math.rad(-20),math.rad(-5),math.rad(0))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C1=CFrame.new(0,0,-0.225)*CFrame.Angles(math.rad(-10),math.rad(25),math.rad(0))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(-0.25,-0.5,0)*CFrame.Angles(math.rad(100),math.rad(0),math.rad(-60))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0.25,-0.25,0.15)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(40))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(2.5),math.rad(-20),math.rad(2))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(5),math.rad(20),math.rad(0))*CFrame.new(0,0,-0.25)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(10))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
		},
		[2]={
			{"nec",{C1=CFrame.Angles(math.rad(-10),math.rad(-15),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rutj",{C1=CFrame.new(0,0,-0.25)*CFrame.Angles(math.rad(-10),math.rad(35),math.rad(0))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rs",{C0=CFrame.new(-0.25,-0.25,0)*CFrame.Angles(math.rad(60),math.rad(0),math.rad(-40))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"ls",{C0=CFrame.new(0.25,-0.25,0.15)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(20))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rh",{C1=CFrame.new(0.1,0.35,-0.25)*CFrame.Angles(math.rad(-5),math.rad(-25),math.rad(5))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(5),math.rad(10),math.rad(0))*CFrame.new(0,0,-0.25)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(10))},{.1,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
		},
		[3]={
			{"nec",{C1=CFrame.Angles(math.rad(-5),math.rad(-45),math.rad(0))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0,-0.05,-0.5)*CFrame.Angles(math.rad(-10),math.rad(50),math.rad(0))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(-0.25,-0.25,0)*CFrame.Angles(math.rad(40),math.rad(20),math.rad(-10))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.1,0.05,-0.65)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(-60))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0.2,0.35,-0.25)*CFrame.Angles(math.rad(20),math.rad(-45),math.rad(10))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(5),math.rad(-10),math.rad(0))*CFrame.new(0,0,-0.25)*CFrame.Angles(math.rad(0),math.rad(0),math.rad(0))},{.1,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[4]={
			{"nec",{C1=CFrame.Angles(math.rad(-5),math.rad(25),math.rad(0))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C1=CFrame.new(-0.15,-0.15,-1.5)*CFrame.Angles(math.rad(-10),math.rad(-60),math.rad(0))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(-0.25,-0.25,0)*CFrame.Angles(math.rad(30),math.rad(20),math.rad(10))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0.25,0.05,-0.35)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(50))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.05,-0.35)*CFrame.Angles(math.rad(15),math.rad(25),math.rad(-15))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(-15),math.rad(50),math.rad(0))*CFrame.new(0,0.35,-0.25)},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
		},
		[5]={
			{"nec",{C1=CFrame.Angles(math.rad(-5),math.rad(25),math.rad(0))},{.2,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C1=CFrame.new(-0.15,-0.15,-1.5)*CFrame.Angles(math.rad(-10),math.rad(-60),math.rad(0))},{.2,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(-0.25,-0.25,0)*CFrame.Angles(math.rad(30),math.rad(20),math.rad(10))},{.2,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0.25,0.05,-0.35)*CFrame.Angles(math.rad(90),math.rad(0),math.rad(50))},{.2,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.05,-0.35)*CFrame.Angles(math.rad(15),math.rad(25),math.rad(-15))},{.2,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(-15),math.rad(50),math.rad(0))*CFrame.new(0,0.35,-0.25)},{.2,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
		}
	},
	IdleSit={
		Waits={
			[1]=.225,
			[2]=.225,
			[3]=.275,
		},
		[1]={
			{"nec",{C0=CFrame.Angles(math.rad(-35),math.rad(-30),math.rad(-10))},{.25,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rutj",{C0=CFrame.new(0,-1.25,1)*CFrame.Angles(math.rad(20),math.rad(-10),math.rad(0))},{.25,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rs",{C0=CFrame.new(-0.1,-0.8,0)*CFrame.Angles(math.rad(-30),math.rad(-60),math.rad(0))},{.25,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"ls",{C0=CFrame.new(0.2,-0.35,-0.1)*CFrame.Angles(math.rad(25),math.rad(-10),math.rad(5))},{.25,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rh",{C0=CFrame.new(0,0.5,-0.25)*CFrame.Angles(math.rad(25),math.rad(-5),math.rad(2.5))},{.25,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"lh",{C0=CFrame.new(0,0.95,-0.5)*CFrame.Angles(math.rad(-6.5),math.rad(15),math.rad(0))},{.25,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
		},
		[2]={
			{"nec",{C0=CFrame.Angles(math.rad(-25),math.rad(0),math.rad(0))},{.25,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C0=CFrame.new(0,-1.65,1)*CFrame.Angles(math.rad(10),math.rad(0),math.rad(0))},{.25,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(-0.1,-0.5,0)*CFrame.Angles(math.rad(-20),math.rad(-60),math.rad(0))},{.25,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0.2,-0.35,-0.1)*CFrame.Angles(math.rad(25),math.rad(-10),math.rad(5))},{.25,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(80),math.rad(-5),math.rad(2.5))},{.25,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C0=CFrame.new(0,1.35,-0.5)*CFrame.Angles(math.rad(5),math.rad(10),math.rad(0))},{.25,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,0,false,0}},
		},
		[3]={
			{"nec",{C0=CFrame.Angles(math.rad(-30),math.rad(0),math.rad(0))},{.3,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(0,-1.65,1.6)*CFrame.Angles(math.rad(20),math.rad(0),math.rad(0))},{.3,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(-0.2,-0.5,.25)*CFrame.Angles(math.rad(-35),math.rad(-30),math.rad(5))},{.3,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.2,-0.5,0.25)*CFrame.Angles(math.rad(-35),math.rad(30),math.rad(-5))},{.3,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(70),math.rad(-5),math.rad(5))},{.3,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(70),math.rad(5),math.rad(-5))},{.3,Enum.EasingStyle.Quad,Enum.EasingDirection.Out,0,false,0}},
		}
	},
	BBlade={
		Waits={
			[1]=.15,
			[2]=.125,
			[3]=.1,
			[4]=.07,
		},
		[1]={
			{"nec",{C0=CFrame.Angles(math.rad(0),math.rad(0),math.rad(0))},{.175,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C0=CFrame.new(0,0,0)},{.175,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(0.25,-0.5,0)*CFrame.Angles(math.rad(10),math.rad(0),math.rad(70))},{.175,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(-0.25,-0.5,0)*CFrame.Angles(math.rad(10),math.rad(0),math.rad(-70))},{.175,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(-5),math.rad(2))},{.175,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(5),math.rad(-2))},{.175,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.25,-0.5,0)*CFrame.Angles(math.rad(10),math.rad(0),math.rad(70))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.175,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.25,-0.5,0)*CFrame.Angles(math.rad(10),math.rad(0),math.rad(-70))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.175,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
		},
		[2]={
			{"nec",{C0=CFrame.Angles(math.rad(-10),math.rad(15),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(0,-0.1,-0.1)*CFrame.Angles(math.rad(-5),math.rad(-15),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0,-0.5,0.15)*CFrame.Angles(math.rad(-10),math.rad(-35),math.rad(50))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.5,-0.75)*CFrame.Angles(math.rad(15),math.rad(-145),math.rad(-70))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.new(0.125,0,-0.2)*CFrame.Angles(math.rad(-5),math.rad(-45),math.rad(10))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.new(0,0.05,-0.35)*CFrame.Angles(math.rad(-7.5),math.rad(15),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0,-0.5,0.15)*CFrame.Angles(math.rad(-10),math.rad(-35),math.rad(50))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(0.1,-0.5,-0.75)*CFrame.Angles(math.rad(15),math.rad(-145),math.rad(-70))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.Out,0,false,0}},
		},
		[3]={
			{"nec",{C0=CFrame.Angles(math.rad(-10),math.rad(5),math.rad(0))},{.125,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C0=CFrame.new(0,-0.1,-0.5)*CFrame.Angles(math.rad(-10),math.rad(15),math.rad(0))},{.125,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(0,-0.5,0.15)*CFrame.Angles(math.rad(-10),math.rad(-20),math.rad(60))},{.125,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0,-0.5,-0.5)*CFrame.Angles(math.rad(15),math.rad(-75),math.rad(-70))},{.125,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C0=CFrame.new(0,0.15,-0.2)*CFrame.Angles(math.rad(-15),math.rad(-10),math.rad(10))},{.125,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C0=CFrame.new(0,0.05,-0.35)*CFrame.Angles(math.rad(-5),math.rad(-5),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0,-0.5,0.15)*CFrame.Angles(math.rad(-10),math.rad(-20),math.rad(60))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(0,-0.5,-0.5)*CFrame.Angles(math.rad(15),math.rad(-75),math.rad(-70))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,false,0}},
		},
		[4]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.09,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,0,-0.575)*CFrame.Angles(math.rad(-5),math.rad(35),math.rad(0))},{.09,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(-10),math.rad(-20),math.rad(80))},{.09,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(15),math.rad(-20),math.rad(-70))},{.09,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.new(0,0.45,-0.55)*CFrame.Angles(math.rad(-30),math.rad(-10),math.rad(10))},{.09,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(0),math.rad(-5),math.rad(0))},{.09,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(-10),math.rad(-20),math.rad(80))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.09,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(15),math.rad(-20),math.rad(-70))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.09,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		}
	},
	BBladeLoop={
		Waits={
			[1]=1/60,
			[2]=1/60,
			[3]=1/60,
			[4]=1/60,
			[5]=1/60,
			[6]=1/60,
			[7]=1/60,
			[8]=1/60,
			[9]=1/60,
			[10]=1/60,
			[11]=1/60,
			[12]=1/60,
			[13]=.03
		},
		[1]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0,-0.325)*CFrame.Angles(math.rad(0),math.rad(60),math.rad(5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.new(0,0.45,-0.55)*CFrame.Angles(math.rad(-25),math.rad(-10),math.rad(10))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(5),math.rad(-5),math.rad(-5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[2]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0,-0.325)*CFrame.Angles(math.rad(0),math.rad(95),math.rad(5))*CFrame.Angles(math.rad(-3),math.rad(0),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.new(0,0.45,-0.55)*CFrame.Angles(math.rad(-20),math.rad(-10),math.rad(10))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.new(0,0,-0.2)*CFrame.Angles(math.rad(10),math.rad(-15),math.rad(-2))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[3]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0,-0.3)*CFrame.Angles(math.rad(0),math.rad(125),math.rad(5))*CFrame.Angles(math.rad(-3),math.rad(0),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.45,-0.55)*CFrame.Angles(math.rad(-15),math.rad(-10),math.rad(7.5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,-0.35)*CFrame.Angles(math.rad(10),math.rad(-15),math.rad(5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[4]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0,-0.3)*CFrame.Angles(math.rad(0),math.rad(155),math.rad(5))*CFrame.Angles(math.rad(-3),math.rad(0),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.3,-0.6)*CFrame.Angles(math.rad(-10),math.rad(-5),math.rad(2.5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,-0.35)*CFrame.Angles(math.rad(10),math.rad(-15),math.rad(10))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[5]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0,-0.3)*CFrame.Angles(math.rad(0),math.rad(195),math.rad(5))*CFrame.Angles(math.rad(-3),math.rad(0),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.new(0,0,-0.45)*CFrame.Angles(math.rad(2.5),math.rad(-5),math.rad(-2.5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.new(0,0,-0.35)*CFrame.Angles(math.rad(10),math.rad(-15),math.rad(10))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[6]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0,-0.3)*CFrame.Angles(math.rad(0),math.rad(225),math.rad(5))*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.new(0,0,-0.3)*CFrame.Angles(math.rad(7.5),math.rad(10),math.rad(-10))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.new(0,0.15,-0.25)*CFrame.Angles(math.rad(-2.5),math.rad(5),math.rad(2.5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[7]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0,-0.3)*CFrame.Angles(math.rad(0),math.rad(255),math.rad(5))*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0,-0.15)*CFrame.Angles(math.rad(5),math.rad(10),math.rad(-10))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.35,-0.35)*CFrame.Angles(math.rad(-10),math.rad(15),math.rad(-2.5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[8]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0,-0.3)*CFrame.Angles(math.rad(0),math.rad(285),math.rad(5))*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0,-0.05)*CFrame.Angles(math.rad(0),math.rad(-10),math.rad(-10))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.35,-0.35)*CFrame.Angles(math.rad(-5),math.rad(15),math.rad(-7.5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[9]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0.05,-0.3)*CFrame.Angles(math.rad(0),math.rad(315),math.rad(5))*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(-5),math.rad(-10),math.rad(-10))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.new(0,0.35,-0.35)*CFrame.Angles(math.rad(-5),math.rad(15),math.rad(-7.5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[10]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0.05,-0.3)*CFrame.Angles(math.rad(0),math.rad(345),math.rad(5))*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.new(0,-0.1,0)*CFrame.Angles(math.rad(-5),math.rad(-10),math.rad(-15))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.new(-0.15,0.35,-0.35)*CFrame.Angles(math.rad(-5),math.rad(35),math.rad(-7.5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[11]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0.05,-0.3)*CFrame.Angles(math.rad(0),math.rad(15),math.rad(5))*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(0))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.25,-0.3)*CFrame.Angles(math.rad(-5),math.rad(-10),math.rad(-15))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,-0.25)*CFrame.Angles(math.rad(0),math.rad(10),math.rad(-7.5))},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.02,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[12]={
			{"nec",{C0=CFrame.Angles(math.rad(-5),math.rad(5),math.rad(0))},{.04,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(-0.1,-0,-0.325)*CFrame.Angles(math.rad(0),math.rad(60),math.rad(5))},{.04,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))},{.04,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))},{.04,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.45,-0.55)*CFrame.Angles(math.rad(-25),math.rad(-10),math.rad(10))},{.04,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0,0)*CFrame.Angles(math.rad(5),math.rad(-5),math.rad(-5))},{.04,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(0.2,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(85))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.04,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.2,-0.5,-0.25)*CFrame.Angles(math.rad(5),math.rad(-20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.04,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
	},
	BBladeStop={
		Waits={
			[1]=.1,
			[2]=.1,
			[3]=.15
		},
		[1]={
			{"nec",{C0=CFrame.Angles(math.rad(5),math.rad(-20),math.rad(0))},{.12,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(0,-0.15,-0.5)*CFrame.Angles(math.rad(-12.5),math.rad(20),math.rad(5))},{.12,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(-0.1,-0.65,-0.6)*CFrame.Angles(math.rad(80),math.rad(0),math.rad(-60))*CFrame.Angles(math.rad(0),math.rad(80),math.rad(0))},{.12,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.15,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(20),math.rad(-80))},{.12,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.new(0,0.1,-0.3)*CFrame.Angles(math.rad(15),math.rad(-20),math.rad(5))},{.12,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.new(0,0.15,-0.4)*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(-5))},{.12,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(-0.1,-0.65,-0.6)*CFrame.Angles(math.rad(80),math.rad(0),math.rad(-60))*CFrame.Angles(math.rad(0),math.rad(80),math.rad(0))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.12,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.15,-0.5,0.15)*CFrame.Angles(math.rad(0),math.rad(20),math.rad(-80))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.12,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[2]={
			{"nec",{C0=CFrame.Angles(math.rad(1.5),math.rad(-10),math.rad(0))},{.12,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rutj",{C0=CFrame.new(0,-0.15,-0.3)*CFrame.Angles(math.rad(-7.5),math.rad(10),math.rad(2.5))},{.12,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rs",{C0=CFrame.new(-0.1,-0.65,-0.6)*CFrame.Angles(math.rad(82.5),math.rad(0),math.rad(-57.5))*CFrame.Angles(math.rad(0),math.rad(80),math.rad(0))},{.12,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"ls",{C0=CFrame.new(-0.05,-0.5,0)*CFrame.Angles(math.rad(0),math.rad(10),math.rad(-37.5))},{.12,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rh",{C0=CFrame.new(0,0,-0.4)*CFrame.Angles(math.rad(27.5),math.rad(-20),math.rad(5))},{.12,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"lh",{C0=CFrame.new(0,0.4,-0.4)*CFrame.Angles(math.rad(-2.5),math.rad(0),math.rad(-5))},{.12,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"r1",{C0=CFrame.new(1,-1,-1.25)*CFrame.new(-0.1,-0.65,-0.6)*CFrame.Angles(math.rad(82.5),math.rad(0),math.rad(-57.5))*CFrame.Angles(math.rad(0),math.rad(80),math.rad(0))*cf(0,-1.8,0)*angles(-90,90,0,true)},{.12,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"r2",{C0=CFrame.new(-1,-1,-1.25)*CFrame.new(-0.05,-0.5,0)*CFrame.Angles(math.rad(0),math.rad(10),math.rad(-37.5))*cf(0,-1.8,0)*angles(-90,-90,0,true)},{.12,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
		},
		[3]={
			{"nec",{C0=CFrame.Angles(math.rad(0),math.rad(0),math.rad(0))},{.15,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C0=CFrame.new(0,0,0)},{.15,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(-0.1,-0.1,0.05)*CFrame.Angles(math.rad(3),math.rad(5),math.rad(-2))},{.15,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,0.05)*CFrame.Angles(math.rad(3),math.rad(-5),math.rad(2))},{.15,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C0=CFrame.Angles(math.rad(0),math.rad(-5),math.rad(2))},{.15,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C0=CFrame.Angles(math.rad(0),math.rad(5),math.rad(-2))},{.15,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		}
	},
	SawCast={
		Waits={
			[1]=.3,
			[2]=.125,
			[3]=.05
		},
		[1]={
			{"nec",{C1=CFrame.Angles(math.rad(-10),math.rad(-10),math.rad(0))},{.35,Enum.EasingStyle.Circular,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(-0.25,-0.85,0.8)*CFrame.Angles(math.rad(-5),math.rad(-30),math.rad(-15))},{.35,Enum.EasingStyle.Circular,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.5,-0.8,-0.5)*CFrame.Angles(math.rad(10),math.rad(0),math.rad(15))*CFrame.Angles(math.rad(0),math.rad(-80),math.rad(0))},{.5,Enum.EasingStyle.Circular,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,0.05)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(-10))},{.35,Enum.EasingStyle.Circular,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0.15,0.5,-0.85)*CFrame.Angles(math.rad(-30),math.rad(0),math.rad(0))*CFrame.Angles(math.rad(0),math.rad(-30),math.rad(15))},{.4,Enum.EasingStyle.Circular,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.75,-0.75)*CFrame.Angles(math.rad(-5),math.rad(35),math.rad(10))},{.35,Enum.EasingStyle.Circular,Enum.EasingDirection.Out,0,false,0}},
		},
		[2]={
			{"nec",{C1=CFrame.Angles(math.rad(-10),math.rad(-10),math.rad(0))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rutj",{C1=CFrame.new(0,-0.15,0.3)*CFrame.Angles(math.rad(-5),math.rad(-5),math.rad(-5))},{.2,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rs",{C0=CFrame.new(0.2,-0.4,-0.4)*CFrame.Angles(math.rad(25),math.rad(0),math.rad(15))*CFrame.Angles(math.rad(0),math.rad(-40),math.rad(-10))},{.3,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,0.05)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(-10))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rh",{C1=CFrame.new(0.15,0.65,-0.75)*CFrame.Angles(math.rad(-10),math.rad(-10),math.rad(5))},{.225,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.15,-0.25)*CFrame.Angles(math.rad(8),math.rad(15),math.rad(5))},{.15,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
		},
		[3]={
			{"nec",{C1=CFrame.Angles(math.rad(0),math.rad(-10),math.rad(0))},{.3,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(-0.1,-0.45,-0.65)*CFrame.Angles(math.rad(-10),math.rad(30),math.rad(5))},{.3,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0,0,-0.5)*CFrame.Angles(math.rad(60),math.rad(0),math.rad(15))*CFrame.Angles(math.rad(0),math.rad(-20),math.rad(0))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0.1,-0.1,0.05)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(-10))},{.3,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0.15,0.45,-0.25)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(0))*CFrame.Angles(math.rad(0),math.rad(-30),math.rad(0))},{.3,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.25,-0.25)*CFrame.Angles(math.rad(-5),math.rad(-5),math.rad(0))},{.3,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
		}
	},
	SpikeBFlip={
		Waits={
			[1]=.075,
			[2]=.17,
			[3]=.225,
			[4]=.275
		},
		[1]={
			{"nec",{C1=CFrame.Angles(math.rad(-10),math.rad(0),math.rad(0))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rutj",{C1=CFrame.new(0,-0.1,-0.1)*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(0))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rs",{C0=CFrame.new(0,-0.1,-0.1)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(2.5))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"ls",{C0=CFrame.new(0,-0.1,-0.1)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(-2.5))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.1,-0.2)*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(0))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.1,-0.1)*CFrame.Angles(math.rad(2.5),math.rad(0),math.rad(0))},{.1,Enum.EasingStyle.Back,Enum.EasingDirection.InOut,0,false,0}},
		},
		[2]={
			{"nec",{C1=CFrame.Angles(math.rad(30),math.rad(0),math.rad(0))},{.3,Enum.EasingStyle.Circular,Enum.EasingDirection.In,0,false,0}},
			{"rutj",{C1=CFrame.new(0,1.65,0)*CFrame.Angles(math.rad(105),math.rad(0),math.rad(0))},{.175,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"rs",{C0=CFrame.new(0.35,-0.2,0)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(75))},{.25,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"ls",{C0=CFrame.new(-0.35,-0.2,0)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(-75))},{.25,Enum.EasingStyle.Sine,Enum.EasingDirection.In,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.1,-0.1)*CFrame.Angles(math.rad(15),math.rad(-5),math.rad(-5))},{.175,Enum.EasingStyle.Back,Enum.EasingDirection.In,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.2,-0.85)*CFrame.Angles(math.rad(-55),math.rad(-10),math.rad(0))},{.285,Enum.EasingStyle.Circular,Enum.EasingDirection.In,0,false,0}},
		},
		[3]={
			{"nec",{C1=CFrame.Angles(math.rad(50),math.rad(0),math.rad(0))},{.35,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0,2.25,0)*CFrame.Angles(math.rad(235),math.rad(0),math.rad(0))},{.25,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0.35,-0.2,0)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(95))},{.3,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(-0.35,-0.2,0)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(-95))},{.3,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.5,-0.5)*CFrame.Angles(math.rad(-5),math.rad(-5),math.rad(-5))},{.3,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.2,-0.15)*CFrame.Angles(math.rad(55),math.rad(-0),math.rad(0))},{.3,Enum.EasingStyle.Linear,Enum.EasingDirection.Out,0,false,0}},
		},
		[4]={
			{"nec",{C1=CFrame.Angles(math.rad(-10),math.rad(0),math.rad(0))},{.25,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rutj",{C1=CFrame.new(0,-0.1,0.1)*CFrame.Angles(math.rad(5),math.rad(0),math.rad(0))},{.45,Enum.EasingStyle.Elastic,Enum.EasingDirection.Out,0,false,0}},
			{"rs",{C0=CFrame.new(0,-0.1,-0.1)*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(-2.5))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"ls",{C0=CFrame.new(0,-0.1,-0.1)*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(2.5))},{.2,Enum.EasingStyle.Back,Enum.EasingDirection.Out,0,false,0}},
			{"rh",{C1=CFrame.new(0,0.1,-0.1)*CFrame.Angles(math.rad(-7.5),math.rad(0),math.rad(0))},{.45,Enum.EasingStyle.Elastic,Enum.EasingDirection.Out,0,false,0}},
			{"lh",{C1=CFrame.new(0,0.1,-0.2)*CFrame.Angles(math.rad(-5),math.rad(0),math.rad(0))},{.45,Enum.EasingStyle.Elastic,Enum.EasingDirection.Out,0,false,0}},
		}
	}
}
