local v3=Vector3.new
return{
	["R6"]={
		["Neck"]={
			["Att0Rotation"]=v3(0,-90,90),
			["Att1Rotation"]=v3(0,-90,90),
			["Position0"]=v3(0,.5,0),
			["Position1"]=v3(0,-.5,0),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=90,
				TwistLowerAngle=-90,
				TwistUpperAngle=90
			}
		},
		["Right Shoulder"]={
			["Att0Rotation"]=v3(0,0,0),
			["Att1Rotation"]=v3(0,0,-90),
			["Position0"]=v3(.75,.333,0),
			["Position1"]=v3(0,.333,0),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=165,
				TwistLowerAngle=-135,
				TwistUpperAngle=135
			}
		},
		["Left Shoulder"]={
			["Att0Rotation"]=v3(0,0,0),
			["Att1Rotation"]=v3(0,0,90),
			["Position0"]=v3(-.75,.333,0),
			["Position1"]=v3(0,.333,0),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=165,
				TwistLowerAngle=-135,
				TwistUpperAngle=135
			}
		},
		["Right Hip"]={
			["Att0Rotation"]=v3(0,-90,-90),
			["Att1Rotation"]=v3(0,-90,-90),
			["Position0"]=v3(.25,-.5,0),
			["Position1"]=v3(0,.5,0),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=100,
				TwistLowerAngle=-45,
				TwistUpperAngle=45
			}
		},
		["Left Hip"]={
			["Att0Rotation"]=v3(0,-90,-90),
			["Att1Rotation"]=v3(0,-90,-90),
			["Position0"]=v3(-.25,-.5,0),
			["Position1"]=v3(0,.5,0),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=100,
				TwistLowerAngle=-45,
				TwistUpperAngle=45
			}
		}
	},
	["R15"]={
		["Neck"]={
			["Att0Rotation"]=v3(0,-90,90),
			["Att1Rotation"]=v3(0,-90,90),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=80,
				TwistLowerAngle=-75,
				TwistUpperAngle=75
			}
		},
		["Waist"]={
			["Att0Rotation"]=v3(0,-90,90),
			["Att1Rotation"]=v3(0,-90,90),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=25,
				TwistLowerAngle=-30,
				TwistUpperAngle=30
			}
		},
		["RightShoulder"]={
			["Att0Rotation"]=v3(0,0,0),
			["Att1Rotation"]=v3(0,0,-90),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=105,
				TwistLowerAngle=-115,
				TwistUpperAngle=115
			}
		},
		["LeftShoulder"]={
			["Att0Rotation"]=v3(0,0,0),
			["Att1Rotation"]=v3(0,0,90),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=105,
				TwistLowerAngle=-115,
				TwistUpperAngle=115
			}
		},
		["RightHip"]={
			["Att0Rotation"]=v3(0,-90,-90),
			["Att1Rotation"]=v3(0,-90,-90),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=80,
				TwistLowerAngle=-35,
				TwistUpperAngle=35
			}
		},
		["LeftHip"]={
			["Att0Rotation"]=v3(0,-90,-90),
			["Att1Rotation"]=v3(0,-90,-90),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=80,
				TwistLowerAngle=-35,
				TwistUpperAngle=35
			}
		},
		["RightElbow"]={
			["Att0Rotation"]=v3(0,0,0),
			["Att1Rotation"]=v3(0,0,0),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=0,
				TwistLowerAngle=105,
				TwistUpperAngle=0
			}
		},
		["LeftElbow"]={
			["Att0Rotation"]=v3(0,0,0),
			["Att1Rotation"]=v3(0,0,0),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=0,
				TwistLowerAngle=105,
				TwistUpperAngle=0
			}
		},
		["RightKnee"]={
			["Att0Rotation"]=v3(0,0,0),
			["Att1Rotation"]=v3(0,0,0),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=0,
				TwistLowerAngle=0,
				TwistUpperAngle=-105
			}
		},
		["LeftKnee"]={
			["Att0Rotation"]=v3(0,0,0),
			["Att1Rotation"]=v3(0,0,0),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=0,
				TwistLowerAngle=0,
				TwistUpperAngle=-105
			}
		},
		["RightWrist"]={
			["Att0Rotation"]=v3(0,-90,-90),
			["Att1Rotation"]=v3(0,-90,-90),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=10,
				TwistLowerAngle=-35,
				TwistUpperAngle=35
			}
		},
		["LeftWrist"]={
			["Att0Rotation"]=v3(0,-90,-90),
			["Att1Rotation"]=v3(0,-90,-90),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=10,
				TwistLowerAngle=-35,
				TwistUpperAngle=35
			}
		},
		["RightAnkle"]={
			["Att0Rotation"]=v3(0,-90,-90),
			["Att1Rotation"]=v3(0,-90,-90),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=10,
				TwistLowerAngle=-35,
				TwistUpperAngle=35
			}
		},
		["LeftAnkle"]={
			["Att0Rotation"]=v3(0,-90,-90),
			["Att1Rotation"]=v3(0,-90,-90),
			["BallSocketProps"]={
				LimitsEnabled=true,
				TwistLimitsEnabled=true,
				UpperAngle=10,
				TwistLowerAngle=-35,
				TwistUpperAngle=35
			}
		}
	}
}
